env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[c9f0ddcf99f98659cb5ff5aa65ff7bb92f2e90ce9c1429e8fec0e965361e457435b62cf760d459fe52360ca278946fcb]"
  TG_TOKEN: "ENCRYPTED[89668822ab9257a1d7f329ee6752b1ef190e3cd479781d7a77c9fb724c660a7424670f2247b432f420e536666c73e13e]"
  TG_CHAT_ID: "ENCRYPTED[f16fe3e3352c38d1a99bce4a537e7ebc84e46df575cfc08ec779b6b951417bc49836bc942442f12a9485495c1175587c]"
  CREDENTIALS: "ENCRYPTED[15a71379be5d1a43552cb7b9e1262d5edf0f145da972f70a659e115b1534b87c8fa035f4482e80cfe5f725ca5434532b]"
  USER: "ENCRYPTED[1f0f7f09739282c0c0aa572b574dec3429c47ce8c02ef98dcbae9eaa542cbb2f0d694e04a6d35fe6dbba6f5b364d3079]"
  EMAIL: "ENCRYPTED[e991d6393361ca84ac5d3faa2162b9e992d018211ae43e72709bbb51108aed16406e62522331ff6b373a8f0ae6588b6d]"
  KBUILD_BUILD_USER: "ENCRYPTED[f3d82e6f5e1d76d6375783705d40cf2389661bb48fd5a02031489b9aab48e8dcd426f1203a6e6f14ff72f99aef4484cd]"
  KBUILD_BUILD_HOST: "ENCRYPTED[835800e749a566e9272e73facb0d8283d8046035c74d404fc8a350dfda6bdd5e3a995ed1fd55813b535b65d2d96cf567]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"
  
# TARGET
  APPS: "SystemUI"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'mobxprjkt'
  timeout_in: 120m
  container:
    image: c3eru/gaspoll:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/memuat_ccache.sh
     
  Repo-pribadi_script:
     - git config --global user.name "$USER"
     - git config --global user.email "$EMAIL"
     - echo "$CREDENTIALS" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - export KBUILD_BUILD_USER=$KBUILD_BUILD_USER
     - export KBUILD_BUILD_HOST=$KBUILD_BUILD_USER
     - export BUILD_USERNAME=$KBUILD_BUILD_USER
     - export BUILD_HOSTNAME=$KBUILD_BUILD_USER


  Sinkronisasi_script:
     - ./script/sinkronisasi.sh
     
  Build-rom_script:
     - ./script/membangun.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/mengunggah.sh
